<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{
    public function getNombreDeFilm(){

        $query = $this->getEntityManager()->createQuery(
            "SELECT count(f) FROM TroiswaBackBundle:Films f"
        );

        //die(var_dump($query->getResult()));

        return $query->getSingleScalarResult();
    }

    public function getNombreDacteurs(){

        $query = $this->getEntityManager()->createQuery(
            "SELECT count(f) FROM TroiswaBackBundle:Acteurs f"
        );

        //die(var_dump($query->getResult()));

        return $query->getSingleScalarResult();
    }

    public function getMaleFemaleActorsNumber(){

        $query = $this->getEntityManager()->createQuery(
            "SELECT f.sexe, count(f) FROM TroiswaBackBundle:Acteurs f GROUP BY f.sexe"
        );

        //die(var_dump($query->getResult()));

        return $query->getResult();
    }

    public function getNombreDeFilmPerGenre(){

        $query = $this->getEntityManager()->createQuery(
            "SELECT g.type, count(f) FROM TroiswaBackBundle:Films f JOIN f.genre g GROUP BY g.type"
        );

        //die(var_dump($query->getResult()));

        return $query->getResult();
    }

    public function getLastMovies($i){

        $query = $this->getEntityManager()->createQuery(
            "SELECT f FROM TroiswaBackBundle:Films f ORDER BY f.dateDeRealisation DESC"
        );

        //die(var_dump($query->getResult()));

        return $query->getResult();
    }



}
